language: java
before_install:
- chmod +x gradlew
deploy:
  provider: heroku
  api_key:
    secure: nj1WngXHCnYPYO9wBSIDjilAnQlXEAjh0p4VaQOL9co9UVua7e/ObaMbNln3y9BfMH83flwMzLca618XE7OuntraHEiSn0ulXDwi4NMaLug6Sp5O0s7s0DqImQA+QgcU9kjwUBOn5uZKpJZfu0LkZ0TsoAEvJHzeHNbkv9zxaxy0zGZ10jZh5rHphxtuxfqNtDMyT9mb7/Sgm8WHbybnAy/P+pVqQiY0VvyE1VMfTEho5v59Qe0GETLIXeNwWq7MSy6emYEpZDsR68BZ/ODweuJale4ZHweijWckZ/wZVWQpPI3/phHLw53r7rtbyZO618ij7+IJ558ucBcx+VsJB5T9sBppqZ8NVStMX+T0t5U+VYThb6jcRvbRFYpgG3u6I/h0MOr5CydDNyFqVRHYDadsN7fpnShYvahUkY8XeRBm9ZxggxI/jHv+piv3/Tcrgb8Ll9S/uzCmeaBKlOdOnz/Y/TvosOZQnsyGgGcayz6AKTHOl7ZHNTAqIZQ8f9rIVev8kjszV+HMQ3qBs6tsfMUQUHRUH8i6CWaZwjQRa3+SBn7Ur4g2F56fvnKpzVfOioF6WmM02LuvMAEYWy4i1kOAC4zUJJATFpNtKvMzQSD+Gyp7IcSYeiQAB3XaEszxD2UShRZY3zXI/xuU75+kgQWlbpuP8aWNeJfavpmV7YM=
  app: kfc-tictactoe
