language: java
deploy:
  provider: heroku
  api_key:
    secure: jV6HjST8uAA2WtzK7IZwFwWJBe2k4p0Bq9/F6TNllVz/nt3RV0eEV5e06NmHyQqERB77hgpS3tR4nwopHPtF+zuUGw8Z2+g/n39m9yeDaHEiNqbqCfWQHnRHaJAIkf8m8I7vLO6VlYVc/NLKEOg1bbxFPPj8kzsMDQTDmrGgq4sxlKZ/xmpbVL4pWnCh2txDMM8IwgHpLyCo0OwE3lXo/ZI1DrqPgM2Z0TsVWgn++E2HXMDQlCviXcrJ8iQ6HmSWTHgpJH3MKz1mrVVOSJNw2a7nSmq2YEHNxfKqVnbnYmVDSs+VRYFtzupn9TG0NMSt2RZ+DpT68Oexgau6QRQ4E3aeZIyqbs/Qd6+emAh+wxfJfg9LbAdMd57g6YYAy0zaRQAJNVZuWPw94hsajtjL8XKDKBamwdu+gDN4xeJ2TV1HGBAIkBW3fYjjaclLWy+tv5U+hEZUAKUQcw7ubx/FL5eHYmTUK5rL/OH72hyZ0cFH1MmsOobpa51WM33UmrTXoq/x9mN+hCuydFYVnEZ6CM2OBi7uJq564f8J9BMiK5rYRT5jN5gk3FWsmdovu3Ma8nSr/OrDP26xbh32oEwuTAK3VaqeuiU3keUdTp5jZyr3CvXdANNC3KEwE9wasV/fHI7RJ9OpLAbcIP06MSiApvP61TFtlPZfz/3NFz4Jm20=
  app: kfc-tictactoe
